const endpoints = {
  REGISTER: "/api/did/register",
  CITIZEN_REGISTER: "/api/citizen-user/register",
  GET_ALL_PRIVACY: "/api/citizen-user/profiles",
  DATE_AVAILABILITY: "/api/appointments/availability",
  APPOINTMENTS: "/api/appointments",
  CREATE_ORGANIZATION: "/api/organization/create-organization",
  GET_ALL_ORGANIZATION: "/api/organization/",
  CREATE_TEMPLATE: "/api/permission-templates/create",
  GEt_ALL_TEMPLATE: "/api/permission-templates/get-all",
  LOGIN: "/api/organization-users/auth/login",
  CREATE_ORGANIZATION_USER: "/api/organization-users/register",
  ORGNIZATION_ROLE: "/api/organization-users/organization",
  GET_ALL_ORGANIZATION_USERS: "/api/organization-users/organization",
  GET_ALL_ORGANIZATIONS_USERS: "/api/organization-users/get-all",
  ORGNIZATION_COUNT: "/api/organization-users/organization",
  ORGNIZATION_COUNTS: "/api/organization-users/users/statistics",
  ORGNIZATION_USER: "/api/organization-users",
  ORGNIZATION_ORG: "/api/organization",
  LICENSE_ISSUED: "/api/vc/driving-license/request",
  LICENSE_STATUS: "/api/vc/driving-license/status",
  LICENSE_VEHICLE_CATEGORIES: "/api/vc/driving-license/vehicle-categories",
  LICENSE_CREATE: "/api/vc/driving-license/credential",
  GET_ALL_LICENSES: "/api/vc/driving-license/request/all",
  SAVE_BIOMETRIC_DATA: "/api/citizen-user/save-biometric",
  CREDENTIAL: "/api/vc/identity/credential",
  CHANGE_LICENSE_IMAGE_STATUS: "/api/vc/photo",
  LICENSE_COUNT: "/api/vc/driving-license/stats",
  FACE_VERIFICATION: "/api/wallet/verify-identity",
  DEEPFAKE_LOGS: "/api/deepfake/logs",
  DEEPFAKE_STATS: "/api/deepfake/logs/stats",
};

export default endpoints;

